### ISSUE TITLE
Move SoftLayer networking configuration from resource pool to networks

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry/bosh-softlayer-cpi-release#135]
Information about network component speed and VLAN IDs for virtual guests are currently specified on the resource pool:

``` yaml
resource_pools:
  small:
    cloud_properties:
      bosh_ip: (( meta.director_ip ))
      domain: softlayer.com
      datacenter:
        name: dal09
      VmNamePrefix: (( meta.environment "-small-" ))
      EphemeralDiskSize: 10
      StartCpus: 2
      MaxMemory: 2048
      HourlyBillingFlag: true
      NetworkComponents:
      - MaxSpeed: 1000
      PrivateNetworkOnlyFlag: true
      PrimaryBackendNetworkComponent:
        NetworkVlan:
          Id: (( meta.softlayer.vlans.private ))
```

This is a strange factoring that gets in the way of some of the bosh model.

Instead of having the information about networks hung off of the resource pool, I think it would be cleaner (and clearer) to have it associated with the networks themselves.  For example, network definitions could look like this:

``` yaml
networks:
- name: cf1-private
  type: dynamic
  dns: 
  - 10.0.80.11
  - 10.0.80.12
  cloud_properties:
    vlan_id: (( meta.softlayer.vlans.private ))
    max_speed: 1000
- name: cf1-public
  type: manual
  subnets:
  - gateway: 169.45.188.209
    range: 169.45.188.208/28
    reserved:
    - 169.45.188.208
    - 169.45.188.209
    - 169.45.188.223
    static:
    - 169.45.188.210-169.45.188.222
    cloud_properties:
      vlan_id: (( meta.softlayer.vlans.public ))
      max_speed: 1000
      public: true
      source_policy_routing: true
```

A job could then clearly distinguish between public and private and, for things like default routes, easily choose to make the private network the default route:

``` yaml
- name: ha_proxy_z1
  instances: 1
  networks:
  - name: cf1-private
  - default:
    - dns
    - gateway
  - name: cf1-public
    static_ips:
    - 169.45.188.210
```

Another nice side effect of this is that the bosh director will have visibility to both IPs associated with the job and will display them on commands like `bosh vms`.

Since the networks and associated cloud properties are already to provided to the external CPI when a VM is created, this should be doable.  The SoftLayer creator would need a just a bit more logic to determine if the VM is only associated with a private network and to verify that there's at most one private and one public vlan used across all attached networks.

**Comment by maximilien** [comment]
@sykesm let me check to see if this was inherited from the legacy CPI. Remember our first priority as we migrate from legacy CPI to the new one is compatibility, to help ease migration.

**Comment by cppforlife** [comment]
+1

**Comment by sykesm** [comment]
@cppforlife can't tel which comment you're endorsing. :)

@maximilien given we're talking about a legacy network configuration vs an explicit network configuration, I think that could be encapsulated as a cloud prop or a cpi configuration element in the config json from the cpi releas.

**Comment by sykesm** [comment]
Working spike can be found here: https://github.com/sykesm/bosh-softlayer-cpi/tree/network-spike

A working concourse cloud-config with this code looks like this:

```yaml
vm_types:
- name: concourse
  cloud_properties:
    bosh_ip: 10.155.248.130
    datacenter: { name: dal09 }
    StartCpus:  4
    MaxMemory:  16384
    EphemeralDiskSize: 100
    HourlyBillingFlag: true
    VmNamePrefix: concourse-furnace-web-
- name: concourse-compilation
  cloud_properties:
    bosh_ip: 10.155.248.130
    datacenter: { name: dal09 }
    StartCpus:  4
    MaxMemory:  8192
    EphemeralDiskSize: 100
    HourlyBillingFlag: true
    VmNamePrefix: concourse-furnace-worker-

disk_types:
- name: small
  disk_size: 50_000

networks:
- name: dynamic
  type: dynamic
  dns:
  - 10.0.80.11
  - 10.0.80.12
  cloud_properties:
    vlan_id: 1113235
- name: static
  type: manual
  subnets:
  - range: 10.155.248.128/28
    gateway: 10.155.248.129
    reserved:
    - 10.155.248.128-10.155.248.130
    - 10.155.248.134-10.155.248.143
    static:
    - 10.155.248.131
    dns:
    - 10.0.80.11
    - 10.0.80.12
    cloud_properties:
      vlan_id: 1113235

compilation:
  workers: 1
  reuse_compilation_vms: true
  vm_type: concourse-compilation
  network: dynamic
```

The spike code has been used to deploy cf, diego, and concourse with a mix of manual and dynamic networks.
