### ISSUE TITLE
How do I specify a dynamic network through subnet instead of vlan id?

### ISSUE THREAD

**Issue by petergtz** [cloudfoundry/bosh-softlayer-cpi-release#191]
We have a configuration in Softlayer that has multiple subnets mapped to one vlan id. How can I force the director to choose IPs strictly from one subnet?

Our `cloud_config.yml` currently contains the following sections:

```
networks:
- name: network1
  type: dynamic
  subnets:
  - az: az1
    dns: [ 10.155.171.25, 10.0.80.11, 10.0.80.12 ]
    cloud_properties:
      PrimaryBackendNetworkComponent:
        NetworkVlan:
          Id: 123456
      PrivateNetworkOnlyFlag: true
```

Is there a way to specify the subnet to use?

/cc @suhlig @smoser-ibm @MarcSchunk

**Comment by mattcui** [comment]
@petergtz I don't think we support this scenario, @jianqiu, please help confirm? Thanks.

**Comment by mattcui** [comment]
@petergtz Confirmed that we don't support it currently, I tagged this issue with "open-for-contribution" and "enhancement".

**Comment by gu-bin** [comment]
Updated the doc through PR https://github.com/cloudfoundry/bosh-softlayer-cpi-release/pull/220

**Comment by MarcSchunk** [comment]
@gu-bin could you pls elaborate why this was closed? We are aware that it is currently not supported. 

However the "open-for-contribution" and "enhancement" kind of indicated for me that this is something you would eventually work on or at least accept contribution.

Please re-open this issue.
cc: @petergtz

**Comment by MarcSchunk** [comment]
@mattcui thx

**Comment by mattcui** [comment]
@petergtz @MarcSchunk I just submitted [PR 232](https://github.com/cloudfoundry/bosh-softlayer-cpi-release/pull/232) to simply address this requirement, there allows to specify `PrimarySubnetId` instead of `Id` (vlan id) in `NetworkVlan`, for examples:

```
networks:
- name: network1
  type: dynamic
  subnets:
  - az: az1
    dns: [ 10.155.171.25, 10.0.80.11, 10.0.80.12 ]
    cloud_properties:
      PrimaryBackendNetworkComponent:
        NetworkVlan:
          PrimarySubnetId: 123456
      PrivateNetworkOnlyFlag: true
```
