### ISSUE TITLE
Unexpected deployment configuration

### ISSUE THREAD

**Issue by DanLavine** [cloudfoundry/bosh-softlayer-cpi-release#209]
When I was deploying bosh via bosh-init, I removed the section for a public network in my bosh.yml.

Specifically:
```
resource_pools:
  - name: vms
    cloud_properties
    PrimaryNetworkComponent:  <---- this line and below
       NetworkVlan:
          Id: <pub vlan>
```

But I still got a public IP address after I deployed. When digging through the code, I saw a property to set (PrivateNetworkOnlyFlag), which when set should give me only a private IP address.

It would be nice to have an updated property configuration list.
