### ISSUE TITLE
Trying to deploy a new director fails with `Failed to get IP address of eth0 in local`

### ISSUE THREAD

**Issue by egurnov** [cloudfoundry/bosh-softlayer-cpi-release#251]
We followed the instructions on https://bosh.io/docs/init-softlayer.html to deploy a new director in Softlayer. After creating the VM, it fails with the error `Failed to get IP address of eth0 in local`. We logged into that machine and there **is** a eth0 interface. So it is not clear why the CPI wouldn't find it.

Could you please help?

Thanks,
Alex and @petergtz 

```
dyn-9-152-97-69:bosh-1 egurnov$ sudo bosh create-env ~/dev/bedrock/bits-service/bits-service-private-config/bosh.yml --state=state.json --vars-store=creds.yml
Password:
Deployment manifest: '/Users/egurnov/dev/bedrock/bits-service/bits-service-private-config/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-softlayer-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-softlayer-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'golang_1.7.1/63889d018ded88d660b01994d7b00c74ce6fe8d5'... Finished (00:00:00)
  Compiling package 'bosh_softlayer_cpi/cd12ba12222d9cedd3628d350c643e2d7247b704'... Finished (00:00:00)
  Installing packages... Finished (00:00:03)
  Rendering job templates... Finished (00:00:00)
  Installing job 'softlayer_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:03)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-softlayer-xen-ubuntu-trusty-go_agent/3421.6'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell '1654181'... Failed (00:10:04)
Failed deploying (00:10:04)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Creating VM:
      Creating vm with stemcell cid '1654181':
        CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Creating Virtual_Guest with agent ID 'ac8d5093-661e-44dd-4f8f-e8960706e393': Failed to get IP address of eth0 in local: Failed to get IP address of eth0","ok_to_retry":false}

Exit code 1
```

**Comment by mattcui** [comment]
Did you specify  `-o bosh-deployment/softlayer/cpi.yml` in `create-env` command?

**Comment by egurnov** [comment]
@mattcui Okay, we got that part to work, but now it fails with:

```
Started deploying
  Creating VM for instance 'bosh/0' from stemcell '1654181'... Finished (00:05:51)
  Waiting for the agent on VM '35611319' to be ready... Failed (00:09:59)
Failed deploying (00:15:51)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.68.205.178:6868/agent: dial tcp 10.68.205.178:6868: getsockopt: connection refused

Exit code 1
```

We followed exactly the docs in https://bosh.io/docs/init-softlayer.html

Also, we checked that the bosh_agent is running on the new VM.

Any ideas?

**Comment by mattcui** [comment]
Seems agent is not started properly, possible to show agent log?

**Comment by petergtz** [comment]
Here's the tail of `/var/vcap/bosh/log/current`:

```
2017-06-29_15:46:00.72105 ********************
2017-06-29_15:46:00.72106 [File System] 2017/06/29 15:46:00 DEBUG - Checking if file exists /sys/class/net/lo/device
2017-06-29_15:46:00.72106 [File System] 2017/06/29 15:46:00 DEBUG - Stat '/sys/class/net/lo/device'
2017-06-29_15:46:00.72113 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Running command 'ifup --no-act eth0'
2017-06-29_15:46:00.72448 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Stdout:
2017-06-29_15:46:00.72450 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Stderr: ifup: interface eth0 already configured
2017-06-29_15:46:00.72451 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Successful: true (0)
2017-06-29_15:46:00.72452 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Running command 'ifup --no-act eth1'
2017-06-29_15:46:00.72789 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Stdout:
2017-06-29_15:46:00.72791 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Stderr: ifup: interface eth1 already configured
2017-06-29_15:46:00.72791 [Cmd Runner] 2017/06/29 15:46:00 DEBUG - Successful: true (0)
2017-06-29_15:46:00.72792 [httpClient] 2017/06/29 15:46:00 DEBUG - Sending GET request to endpoint 'https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json'
2017-06-29_15:46:00.72793 [attemptRetryStrategy] 2017/06/29 15:46:00 DEBUG - Making attempt #0 for *http.requestRetryable
2017-06-29_15:46:00.72810 [clientRetryable] 2017/06/29 15:46:00 DEBUG - [requestID=3cbe0e64-a834-418b-6e25-c1570e906929] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json' }
2017-06-29_15:46:00.81508 [unlimitedRetryStrategy] 2017/06/29 15:46:00 DEBUG - Making attempt #1
2017-06-29_15:46:00.81512 [DelayedAuditLogger] 2017/06/29 15:46:00 ERROR - Unix syslog delivery error
2017-06-29_15:46:00.91551 [unlimitedRetryStrategy] 2017/06/29 15:46:00 DEBUG - Making attempt #2
2017-06-29_15:46:00.91554 [DelayedAuditLogger] 2017/06/29 15:46:00 ERROR - Unix syslog delivery error
2017-06-29_15:46:01.01605 [unlimitedRetryStrategy] 2017/06/29 15:46:01 DEBUG - Making attempt #3
2017-06-29_15:46:01.01608 [DelayedAuditLogger] 2017/06/29 15:46:01 ERROR - Unix syslog delivery error
2017-06-29_15:46:01.11646 [unlimitedRetryStrategy] 2017/06/29 15:46:01 DEBUG - Making attempt #4
2017-06-29_15:46:01.11653 [DelayedAuditLogger] 2017/06/29 15:46:01 ERROR - Unix syslog delivery error
2017-06-29_15:46:01.21700 [unlimitedRetryStrategy] 2017/06/29 15:46:01 DEBUG - Making attempt #5
2017-06-29_15:46:01.21702 [DelayedAuditLogger] 2017/06/29 15:46:01 ERROR - Unix syslog delivery error
2017-06-29_15:46:01.31717 [unlimitedRetryStrategy] 2017/06/29 15:46:01 DEBUG - Making attempt #6
2017-06-29_15:46:01.31747 [DelayedAuditLogger] 2017/06/29 15:46:01 ERROR - Unix syslog delivery error
2017-06-29_15:46:01.39889 [settingsService] 2017/06/29 15:46:01 ERROR - Failed loading settings via fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
2017-06-29_15:46:01.39891 [settingsService] 2017/06/29 15:46:01 ERROR - Failed reading settings from file Opening file /var/vcap/bosh/settings.json: open /var/vcap/bosh/settings.json: no such file or directory
2017-06-29_15:46:01.39895 [File System] 2017/06/29 15:46:01 DEBUG - Reading file /var/vcap/bosh/settings.json
2017-06-29_15:46:01.39896 [main] 2017/06/29 15:46:01 ERROR - App setup Running bootstrap: Fetching settings: Invoking settings fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
2017-06-29_15:46:01.39897 [main] 2017/06/29 15:46:01 ERROR - Agent exited with error: Running bootstrap: Fetching settings: Invoking settings fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
```

**Comment by mattcui** [comment]
Need to show us your deployment yml (hide all sensitive data there).

**Comment by petergtz** [comment]
Invoked as:
```bash
$ sudo bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/softlayer/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=<redacted> \
    -v internal_gw=<redacted> \
    -v internal_ip=<redacted> \
    -v sl_datacenter=ams01 \
    -v sl_vm_domain=flintstone.ams \
    -v sl_vm_name_prefix=director \
    -v sl_vlan_public=<redacted> \
    -v sl_vlan_private=<redacted> \
    -v sl_username=<redacted> \
    -v sl_api_key=<redacted>
```
With `bosh.yml` (taken as is from [cloudfoundry/bosh-deployment](https://github.com/cloudfoundry/bosh-deployment)):
```yaml
---
name: bosh

releases:
- name: bosh
  version: "262.1"
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-262.1-ubuntu-trusty-3421.9-20170621-055124-244370454-20170621055129.tgz?versionId=lxNGZVeHOlvxh4LyMgNxnHC8wczKDP70
  sha1: 1ad2a2b9913c20eac5f27a5e9ad71739c633d37d

resource_pools:
- name: vms
  network: default
  env:
    bosh:
      password: '*'
      mbus:
        cert: ((mbus_bootstrap_ssl))

disk_pools:
- name: disks
  disk_size: 32_768

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static: [((internal_ip))]
    dns: [8.8.8.8]

instance_groups:
- name: bosh
  instances: 1
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: default
    static_ips: [((internal_ip))]
  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: ((nats_password))
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: ((postgres_password))
      database: bosh
      adapter: postgres
    blobstore:
      address: ((internal_ip))
      port: 25250
      provider: dav
      director:
        user: director
        password: ((blobstore_director_password))
      agent:
        user: agent
        password: ((blobstore_agent_password))
    director:
      address: 127.0.0.1
      name: ((director_name))
      db: *db
      flush_arp: true
      enable_post_deploy: true
      generate_vm_passwords: true
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      workers: 4
      events:
        record_events: true
      ssl:
        key: ((director_ssl.private_key))
        cert: ((director_ssl.certificate))
      user_management:
        provider: local
        local:
          users:
          - name: admin
            password: ((admin_password))
          - name: hm
            password: ((hm_password))
    hm:
      director_account:
        user: hm
        password: ((hm_password))
        ca_cert: ((director_ssl.ca))
      resurrector_enabled: true
    ntp: &ntp
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222

cloud_provider:
  mbus: https://mbus:((mbus_bootstrap_password))@((internal_ip)):6868
  cert: ((mbus_bootstrap_ssl))
  properties:
    agent: {mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp

variables:
- name: admin_password
  type: password
- name: blobstore_director_password
  type: password
- name: blobstore_agent_password
  type: password
- name: hm_password
  type: password
- name: mbus_bootstrap_password
  type: password
- name: nats_password
  type: password
- name: postgres_password
  type: password
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: mbus_bootstrap_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]
- name: director_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: ((internal_ip))
    alternative_names: [((internal_ip))]
```

And `cpi.yml`:
```yaml
---
- type: replace
  path: /releases/-
  value:
    name: bosh-softlayer-cpi
    version: 20
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-softlayer-cpi-release?v=20
    sha1: 081d88b8f869fb779574db767019db4927777661
    # name: bosh-softlayer-cpi
    # version: 10
    # url: https://bosh.io/d/github.com/cloudfoundry/bosh-softlayer-cpi-release?v=10
    # sha1: f0209e5565b64beccffa4482945c865890b5ca71

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-softlayer-xen-ubuntu-trusty-go_agent?v=3421.6
    sha1: 6f5a7cf10755e9ce0d659664f5aa44eaf533e114

- type: replace
  path: /resource_pools/name=vms/env
  value:
    bosh:
      keep_root_password: true

# Configure sizes
- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    domain: ((sl_vm_domain))
    vmNamePrefix: ((sl_vm_name_prefix))
    ephemeralDiskSize: 100
    startCpus: 4
    maxMemory: 8192
    deployedByBoshcli: true
    hourlyBillingFlag: true
    networkComponents:
    - maxSpeed: 100
    datacenter:
      name: ams01

- type: replace
  path: /disk_pools/name=disks/disk_size
  value: 20_000

- type: replace
  path: /networks/name=default/subnets/0/dns
  value: [8.8.8.8, 10.0.80.11, 10.0.80.12]

- type: replace
  path: /networks/-
  value:
    name: dynamic
    type: dynamic
    dns: [8.8.8.8, 10.0.80.11, 10.0.80.12]
    cloud_properties:
      PrimaryNetworkComponent:
        NetworkVlan:
          Id: ((sl_vlan_public))
      PrimaryBackendNetworkComponent:
        NetworkVlan:
          Id: ((sl_vlan_private))

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: softlayer_cpi
    release: bosh-softlayer-cpi

- type: replace
  path: /instance_groups/name=bosh/networks/-
  value:
    name: dynamic

- type: replace
  path: /instance_groups/name=bosh/networks/name=default/default?
  value: [gateway, dns]

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: softlayer_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

- type: replace
  path: /instance_groups/name=bosh/properties/softlayer?
  value: &softlayer
    username: ((sl_username))
    apiKey: ((sl_api_key))

- type: replace
  path: /cloud_provider/properties/softlayer?
  value: *softlayer
```

We tried version 10 and version 20 of the CPI.

**Comment by petergtz** [comment]
The agent is running in a loop, constantly trying to get those settings, but I'm not sure exactly why it fails:

```
2017-06-30_14:25:42.79286 [File System] 2017/06/30 14:25:42 DEBUG - Checking if file exists /sys/class/net/lo/device
2017-06-30_14:25:42.79286 [File System] 2017/06/30 14:25:42 DEBUG - Stat '/sys/class/net/lo/device'
2017-06-30_14:25:42.79289 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Running command 'ifup --no-act eth0'
2017-06-30_14:25:42.79584 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Stdout:
2017-06-30_14:25:42.79586 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Stderr: ifup: interface eth0 already configured
2017-06-30_14:25:42.79587 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Successful: true (0)
2017-06-30_14:25:42.79588 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Running command 'ifup --no-act eth1'
2017-06-30_14:25:42.79911 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Stdout:
2017-06-30_14:25:42.79914 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Stderr: ifup: interface eth1 already configured
2017-06-30_14:25:42.79915 [Cmd Runner] 2017/06/30 14:25:42 DEBUG - Successful: true (0)
2017-06-30_14:25:42.79916 [httpClient] 2017/06/30 14:25:42 DEBUG - Sending GET request to endpoint 'https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json'
2017-06-30_14:25:42.79917 [attemptRetryStrategy] 2017/06/30 14:25:42 DEBUG - Making attempt #0 for *http.requestRetryable
2017-06-30_14:25:42.79928 [clientRetryable] 2017/06/30 14:25:42 DEBUG - [requestID=8e61ae4d-8cf2-4ae6-4835-8d139daa835f] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json' }
2017-06-30_14:25:42.88690 [unlimitedRetryStrategy] 2017/06/30 14:25:42 DEBUG - Making attempt #1
2017-06-30_14:25:42.88712 [DelayedAuditLogger] 2017/06/30 14:25:42 ERROR - Unix syslog delivery error
2017-06-30_14:25:42.98755 [DelayedAuditLogger] 2017/06/30 14:25:42 ERROR - Unix syslog delivery error
2017-06-30_14:25:42.98759 [unlimitedRetryStrategy] 2017/06/30 14:25:42 DEBUG - Making attempt #2
2017-06-30_14:25:43.08804 [DelayedAuditLogger] 2017/06/30 14:25:43 ERROR - Unix syslog delivery error
2017-06-30_14:25:43.08807 [unlimitedRetryStrategy] 2017/06/30 14:25:43 DEBUG - Making attempt #3
2017-06-30_14:25:43.18831 [unlimitedRetryStrategy] 2017/06/30 14:25:43 DEBUG - Making attempt #4
2017-06-30_14:25:43.18851 [DelayedAuditLogger] 2017/06/30 14:25:43 ERROR - Unix syslog delivery error
2017-06-30_14:25:43.28896 [DelayedAuditLogger] 2017/06/30 14:25:43 ERROR - Unix syslog delivery error
2017-06-30_14:25:43.28908 [unlimitedRetryStrategy] 2017/06/30 14:25:43 DEBUG - Making attempt #5
2017-06-30_14:25:43.38950 [DelayedAuditLogger] 2017/06/30 14:25:43 ERROR - Unix syslog delivery error
2017-06-30_14:25:43.38953 [unlimitedRetryStrategy] 2017/06/30 14:25:43 DEBUG - Making attempt #6
2017-06-30_14:25:43.48986 [DelayedAuditLogger] 2017/06/30 14:25:43 ERROR - Unix syslog delivery error
2017-06-30_14:25:43.48989 [unlimitedRetryStrategy] 2017/06/30 14:25:43 DEBUG - Making attempt #7
2017-06-30_14:25:43.52131 [settingsService] 2017/06/30 14:25:43 ERROR - Failed loading settings via fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
2017-06-30_14:25:43.52134 [settingsService] 2017/06/30 14:25:43 ERROR - Failed reading settings from file Opening file /var/vcap/bosh/settings.json: open /var/vcap/bosh/settings.json: no such file or directory
2017-06-30_14:25:43.52136 [main] 2017/06/30 14:25:43 ERROR - App setup Running bootstrap: Fetching settings: Invoking settings fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
2017-06-30_14:25:43.52137 [main] 2017/06/30 14:25:43 ERROR - Agent exited with error: Running bootstrap: Fetching settings: Invoking settings fetcher: Getting registry endpoint: Getting user data: Decoding url encoded user data: illegal base64 data at input byte 0
2017-06-30_14:25:43.52141 [File System] 2017/06/30 14:25:43 DEBUG - Reading file /var/vcap/bosh/settings.json
2017-06-30_14:25:44.54573 [main] 2017/06/30 14:25:44 DEBUG - Starting agent
2017-06-30_14:25:44.54575 [File System] 2017/06/30 14:25:44 DEBUG - Reading file /var/vcap/bosh/agent.json
2017-06-30_14:25:44.54576 [File System] 2017/06/30 14:25:44 DEBUG - Read content
2017-06-30_14:25:44.54577 ********************
2017-06-30_14:25:44.54578 {
2017-06-30_14:25:44.54579   "Platform": {
2017-06-30_14:25:44.54580     "Linux": {
2017-06-30_14:25:44.54581       "CreatePartitionIfNoEphemeralDisk": true,
2017-06-30_14:25:44.54581       "ScrubEphemeralDisk": true
2017-06-30_14:25:44.54582     }
2017-06-30_14:25:44.54583   },
2017-06-30_14:25:44.54584   "Infrastructure": {
2017-06-30_14:25:44.54584     "Settings": {
2017-06-30_14:25:44.54585       "Sources": [
2017-06-30_14:25:44.54586         {
2017-06-30_14:25:44.54587           "Type": "HTTP",
2017-06-30_14:25:44.54588           "URI": "https://api.service.softlayer.com",
2017-06-30_14:25:44.54588           "UserDataPath": "/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json",
2017-06-30_14:25:44.54589           "InstanceIDPath": "/rest/v3.1/SoftLayer_Resource_Metadata/getId.json"
2017-06-30_14:25:44.54590         }
2017-06-30_14:25:44.54591       ],
2017-06-30_14:25:44.54592       "UseRegistry": true
2017-06-30_14:25:44.54592     }
2017-06-30_14:25:44.54593   }
2017-06-30_14:25:44.54594 }
2017-06-30_14:25:44.54595
2017-06-30_14:25:44.54595 ********************
2017-06-30_14:25:44.54774 [File System] 2017/06/30 14:25:44 DEBUG - Reading file /var/vcap/bosh/etc/stemcell_version
2017-06-30_14:25:44.54785 [File System] 2017/06/30 14:25:44 DEBUG - Read content
2017-06-30_14:25:44.54789 ********************
2017-06-30_14:25:44.54793 3421.6
2017-06-30_14:25:44.54796 ********************
2017-06-30_14:25:44.54804 [File System] 2017/06/30 14:25:44 DEBUG - Reading file /var/vcap/bosh/etc/stemcell_git_sha1
2017-06-30_14:25:44.54812 [File System] 2017/06/30 14:25:44 DEBUG - Read content
2017-06-30_14:25:44.54814 ********************
2017-06-30_14:25:44.54815 db70314b99509ae9f5fac35dc4c0b524f50515e1
2017-06-30_14:25:44.54816 ********************
2017-06-30_14:25:44.54821 [App] 2017/06/30 14:25:44 INFO - Running on stemcell version '3421.6' (git: db70314b99509ae9f5fac35dc4c0b524f50515e1)
2017-06-30_14:25:44.54826 [File System] 2017/06/30 14:25:44 DEBUG - Checking if file exists /var/vcap/bosh/agent_state.json
2017-06-30_14:25:44.54841 [File System] 2017/06/30 14:25:44 DEBUG - Stat '/var/vcap/bosh/agent_state.json'
2017-06-30_14:25:44.54843 [Cmd Runner] 2017/06/30 14:25:44 DEBUG - Running command 'bosh-agent-rc'
2017-06-30_14:25:44.54844 [unlimitedRetryStrategy] 2017/06/30 14:25:44 DEBUG - Making attempt #0
2017-06-30_14:25:44.54871 [DelayedAuditLogger] 2017/06/30 14:25:44 ERROR - Unix syslog delivery error
2017-06-30_14:25:44.55544 [Cmd Runner] 2017/06/30 14:25:44 DEBUG - Stdout:
2017-06-30_14:25:44.55547 [Cmd Runner] 2017/06/30 14:25:44 DEBUG - Stderr:
2017-06-30_14:25:44.55548 [Cmd Runner] 2017/06/30 14:25:44 DEBUG - Successful: true (0)
2017-06-30_14:25:44.55549 [settingsService] 2017/06/30 14:25:44 DEBUG - Loading settings from fetcher
2017-06-30_14:25:44.55550 [File System] 2017/06/30 14:25:44 DEBUG - Glob '/sys/class/net/*'
2017-06-30_14:25:44.55551 [File System] 2017/06/30 14:25:44 DEBUG - Checking if file exists /sys/class/net/eth0/device
2017-06-30_14:25:44.55552 [File System] 2017/06/30 14:25:44 DEBUG - Stat '/sys/class/net/eth0/device'
2017-06-30_14:25:44.55561 [File System] 2017/06/30 14:25:44 DEBUG - Reading file /sys/class/net/eth0/address
```

Doing the call manually with `curl`, gives me the follwing:

```
curl -vvv https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json
* Hostname was NOT found in DNS cache
*   Trying 10.0.80.88...
* Connected to api.service.softlayer.com (10.0.80.88) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: CN=api.service.softlayer.com
* 	 start date: 2016-06-06 00:00:00 GMT
* 	 expire date: 2018-08-05 23:59:59 GMT
* 	 subjectAltName: api.service.softlayer.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA
* 	 SSL certificate verify ok.
> GET /rest/v3.1/SoftLayer_Resource_Metadata/getUserMetadata.json HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.service.softlayer.com
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 30 Jun 2017 14:26:12 GMT
* Server Apache is not blacklisted
< Server: Apache
< X-Frame-Options: SAMEORIGIN
< Content-Length: 126
< Vary: Accept-Encoding
< Connection: close
< Content-Type: application/json
<
* Closing connection 0
* SSLv3, TLS alert, Client hello (1):
"{\"registry\":{\"endpoint\":\"http:\/\/:@:0\"},\"server\":{\"name\":\"vm-d878b13a-a1a6-42ad-6464-0abba69cd795\"},\"dns\":{}}"/:~# Connection to 10.68.205.182 closed by remote host.
Connection to 10.68.205.182 closed.
```

Any ideas, @mattcui?

/cc @suhlig

**Comment by mattcui** [comment]
@petergtz Could you please have a try with the `bluemix` stemcell?  There should be some compatibility issue in agent of `softlayer` community stemcell. We will try to fix it soon.

https://s3.amazonaws.com/bosh-softlayer-stemcells-bluemix/light-bosh-stemcell-3421.9.3-bluemix-xen-ubuntu-trusty-go_agent.tgz

**Comment by petergtz** [comment]
@mattcui Thanks, that helped. The bosh_agent seems work now.

However, we get the following error now:

```
Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@director.flintstone.ams:6868/agent: x509: certificate has expired or is not yet valid

Exit code 1
```

Let me give you some context: `@director.flintstone.ams` is in there because I replaced `(( internal_ip ))` with this hard-coded string. My understanding is, that `internal_ip` should be the bosh-director IP. However, that IP doesn't exist before the director VM is created.

In fact, this is what our bosh.yml looks like now:

```yaml
---
name: bosh

releases:
- name: bosh
  version: "262.1"
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-262.1-ubuntu-trusty-3421.9-20170621-055124-244370454-20170621055129.tgz?versionId=lxNGZVeHOlvxh4LyMgNxnHC8wczKDP70
  sha1: 1ad2a2b9913c20eac5f27a5e9ad71739c633d37d

resource_pools:
- name: vms
  network: default
  env:
    bosh:
      password: '*'
      mbus:
        cert: ((mbus_bootstrap_ssl))

disk_pools:
- name: disks
  disk_size: 32_768

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    static: [((internal_ip))]
    dns: [8.8.8.8]

instance_groups:
- name: bosh
  instances: 1
  jobs:
  - {name: nats, release: bosh}
  - {name: postgres-9.4, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  resource_pool: vms
  persistent_disk_pool: disks
  networks:
  - name: default
    static_ips: [((internal_ip))]
  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: ((nats_password))
    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: ((postgres_password))
      database: bosh
      adapter: postgres
    blobstore:
      address: director.flintstone.ams
      port: 25250
      provider: dav
      director:
        user: director
        password: ((blobstore_director_password))
      agent:
        user: agent
        password: ((blobstore_agent_password))
    director:
      address: 127.0.0.1
      name: ((director_name))
      db: *db
      flush_arp: true
      enable_post_deploy: true
      generate_vm_passwords: true
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      workers: 4
      events:
        record_events: true
      ssl:
        key: ((director_ssl.private_key))
        cert: ((director_ssl.certificate))
      user_management:
        provider: local
        local:
          users:
          - name: admin
            password: ((admin_password))
          - name: hm
            password: ((hm_password))
    hm:
      director_account:
        user: hm
        password: ((hm_password))
        ca_cert: ((director_ssl.ca))
      resurrector_enabled: true
    ntp: &ntp
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    agent:
      mbus: nats://nats:((nats_password))@director.flintstone.ams:4222

cloud_provider:
  mbus: https://mbus:((mbus_bootstrap_password))@director.flintstone.ams:6868
  cert: ((mbus_bootstrap_ssl))
  properties:
    agent: {mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp

variables:
- name: admin_password
  type: password
- name: blobstore_director_password
  type: password
- name: blobstore_agent_password
  type: password
- name: hm_password
  type: password
- name: mbus_bootstrap_password
  type: password
- name: nats_password
  type: password
- name: postgres_password
  type: password
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: mbus_bootstrap_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: director.flintstone.ams
    alternative_names: [director.flintstone.ams]
- name: director_ssl
  type: certificate
  options:
    ca: default_ca
    common_name: director.flintstone.ams
    alternative_names: [director.flintstone.ams]
```

Our assumption is now that the certificates created do not work with the `director.flintstone.ams` URL. Is this correct? And if so, how can we fix it?
