### ISSUE TITLE
Add GeSec scan into travis

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#308]

**Comment by edwardstudy** [comment]
First fly result: https://travis-ci.org/cloudfoundry/bosh-softlayer-cpi-release/builds/460601751#L4208-L4214

```
Results:
Summary:
   Files: 123
   Lines: 17269
   Nosec: 10
```
